services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    Symfony\Component\Console\Command\Command: 
      tags: ['app.command']

  ProjectEuler\:
    resource: '../src/*'

  ProjectEuler\App:
    class: \ProjectEuler\App
    public: true
    arguments:
      - !tagged_iterator app.command

  ProjectEuler\Commands\:
    resource: '../src/Commands/*'
