services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    Symfony\Component\Console\Command\Command: 
      tags: ['app.command']

  ProjectEuler\:
    resource: '../src/*'

  ProjectEuler\Commands\:
    resource: '../src/Commands/*'
